1592142508.694 : radical.saga         : 6126  : 139808233285376 : ERROR    : skip adaptor radical.saga.adaptors.redis.redis_advert: import failed (No module named 'redis')
Traceback (most recent call last):
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/engine/engine.py", line 174, in _load_adaptors
    adaptor_module = ru.import_module(module_name)
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/utils/modules.py", line 21, in import_module
    mod = __import__(name)
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/adaptors/redis/redis_advert.py", line 9, in <module>
    from . import redis_namespace as rns
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/adaptors/redis/redis_namespace.py", line 52, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
1592142520.172 : radical.saga         : 6222  : 140214762497792 : ERROR    : skip adaptor radical.saga.adaptors.redis.redis_advert: import failed (No module named 'redis')
Traceback (most recent call last):
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/engine/engine.py", line 174, in _load_adaptors
    adaptor_module = ru.import_module(module_name)
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/utils/modules.py", line 21, in import_module
    mod = __import__(name)
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/adaptors/redis/redis_advert.py", line 9, in <module>
    from . import redis_namespace as rns
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/adaptors/redis/redis_namespace.py", line 52, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
1592142541.631 : radical.saga         : 6302  : 139631997720320 : ERROR    : skip adaptor radical.saga.adaptors.redis.redis_advert: import failed (No module named 'redis')
Traceback (most recent call last):
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/engine/engine.py", line 174, in _load_adaptors
    adaptor_module = ru.import_module(module_name)
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/utils/modules.py", line 21, in import_module
    mod = __import__(name)
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/adaptors/redis/redis_advert.py", line 9, in <module>
    from . import redis_namespace as rns
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/adaptors/redis/redis_namespace.py", line 52, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
1592142566.018 : radical.saga         : 6454  : 139971945965312 : ERROR    : skip adaptor radical.saga.adaptors.redis.redis_advert: import failed (No module named 'redis')
Traceback (most recent call last):
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/engine/engine.py", line 174, in _load_adaptors
    adaptor_module = ru.import_module(module_name)
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/utils/modules.py", line 21, in import_module
    mod = __import__(name)
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/adaptors/redis/redis_advert.py", line 9, in <module>
    from . import redis_namespace as rns
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/adaptors/redis/redis_namespace.py", line 52, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
1592142566.637 : radical.saga         : 6540  : 140586525968128 : ERROR    : skip adaptor radical.saga.adaptors.redis.redis_advert: import failed (No module named 'redis')
Traceback (most recent call last):
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/engine/engine.py", line 174, in _load_adaptors
    adaptor_module = ru.import_module(module_name)
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/utils/modules.py", line 21, in import_module
    mod = __import__(name)
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/adaptors/redis/redis_advert.py", line 9, in <module>
    from . import redis_namespace as rns
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/adaptors/redis/redis_namespace.py", line 52, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
1592142567.170 : radical.saga         : 6551  : 140332763997952 : ERROR    : skip adaptor radical.saga.adaptors.redis.redis_advert: import failed (No module named 'redis')
Traceback (most recent call last):
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/engine/engine.py", line 174, in _load_adaptors
    adaptor_module = ru.import_module(module_name)
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/utils/modules.py", line 21, in import_module
    mod = __import__(name)
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/adaptors/redis/redis_advert.py", line 9, in <module>
    from . import redis_namespace as rns
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/adaptors/redis/redis_namespace.py", line 52, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
