1592144553.926 : radical.saga         : 11218 : 139806609454848 : ERROR    : skip adaptor radical.saga.adaptors.redis.redis_advert: import failed (No module named 'redis')
Traceback (most recent call last):
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/engine/engine.py", line 174, in _load_adaptors
    adaptor_module = ru.import_module(module_name)
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/utils/modules.py", line 21, in import_module
    mod = __import__(name)
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/adaptors/redis/redis_advert.py", line 9, in <module>
    from . import redis_namespace as rns
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/adaptors/redis/redis_namespace.py", line 52, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
1592144565.833 : radical.saga         : 11352 : 140444869216000 : ERROR    : skip adaptor radical.saga.adaptors.redis.redis_advert: import failed (No module named 'redis')
Traceback (most recent call last):
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/engine/engine.py", line 174, in _load_adaptors
    adaptor_module = ru.import_module(module_name)
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/utils/modules.py", line 21, in import_module
    mod = __import__(name)
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/adaptors/redis/redis_advert.py", line 9, in <module>
    from . import redis_namespace as rns
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/adaptors/redis/redis_namespace.py", line 52, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
1592144587.241 : radical.saga         : 11429 : 140361136580352 : ERROR    : skip adaptor radical.saga.adaptors.redis.redis_advert: import failed (No module named 'redis')
Traceback (most recent call last):
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/engine/engine.py", line 174, in _load_adaptors
    adaptor_module = ru.import_module(module_name)
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/utils/modules.py", line 21, in import_module
    mod = __import__(name)
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/adaptors/redis/redis_advert.py", line 9, in <module>
    from . import redis_namespace as rns
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/adaptors/redis/redis_namespace.py", line 52, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
1592144610.800 : radical.saga         : 11561 : 139998387701504 : ERROR    : skip adaptor radical.saga.adaptors.redis.redis_advert: import failed (No module named 'redis')
Traceback (most recent call last):
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/engine/engine.py", line 174, in _load_adaptors
    adaptor_module = ru.import_module(module_name)
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/utils/modules.py", line 21, in import_module
    mod = __import__(name)
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/adaptors/redis/redis_advert.py", line 9, in <module>
    from . import redis_namespace as rns
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/adaptors/redis/redis_namespace.py", line 52, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
1592144611.310 : radical.saga         : 11578 : 139820541609728 : ERROR    : skip adaptor radical.saga.adaptors.redis.redis_advert: import failed (No module named 'redis')
Traceback (most recent call last):
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/engine/engine.py", line 174, in _load_adaptors
    adaptor_module = ru.import_module(module_name)
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/utils/modules.py", line 21, in import_module
    mod = __import__(name)
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/adaptors/redis/redis_advert.py", line 9, in <module>
    from . import redis_namespace as rns
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/adaptors/redis/redis_namespace.py", line 52, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
1592144611.852 : radical.saga         : 11589 : 140308362831616 : ERROR    : skip adaptor radical.saga.adaptors.redis.redis_advert: import failed (No module named 'redis')
Traceback (most recent call last):
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/engine/engine.py", line 174, in _load_adaptors
    adaptor_module = ru.import_module(module_name)
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/utils/modules.py", line 21, in import_module
    mod = __import__(name)
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/adaptors/redis/redis_advert.py", line 9, in <module>
    from . import redis_namespace as rns
  File "/home/aymen/ve/parsl-env/lib/python3.7/site-packages/radical/saga/adaptors/redis/redis_namespace.py", line 52, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
